spring:
  application:
    name: consumer

feign:
  hystrix:
    enabled: true

#hystrix超时时间要大于ribbon超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectTimeout: 1000
  #  默认5s
  ReadTimeout: 5000
  #  这里有个bug，此参数说转发到另一个节点重试，但是当只有一个节点时候会在这个节点再重试一遍
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 5000

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

server:
  port: 8010

#####rocket-mq######
apache:
  rocketmq:
    consumer:
      PushConsumer: victor_test
      instacneName: victor_test_Consumer
    producer:
      producerGroup: victor_test_Producer
      instacneName: victor_test_Producer
    namesrvAddr: 47.100.249.163:9876
    topic: VictorTest
    tag: VictorTest
#####rocket-mq######
